config/routes.rb
Portfolio::Application.routes.draw do
  scope ":locale" do

    devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks"}

    resources :posts do
      resources :comments
    end

    resources :projects do
      resources :comments
    end

    devise_scope :user do
      get 'sign_out', to: 'devise/sessions#destroy', as: :sign_out
    end

  end
   root :to => 'home#index'

end

app/models/project.rb
class Project < ActiveRecord::Base
  attr_accessible :name, :technologies_used, :image, :remote_image_url
  has_many :comments, as: :commentable
  mount_uploader :image, ImageUploader

  validates :technologies_used, presence: true

  validates :name, length: { in: 4..255 }

  after_save :enqueue_image

  def image_name
    File.basename(image.path || image.filename) if image
  end

  def enqueue_image
    ImageWorker.perform_async(id, key) if key.present?
  end

  class ImageWorker
    include Sidekiq::Worker

    def perform(id, key)
      project = Project.find(id)
      project.key = key
      project.remote_image_url = project.image.direct_fog_url(with_path: true)
      project.save!
      project.update_column(:image_processed, true)
    end
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_filter :set_project, only: [:show, :edit, :update, :destroy]

  def index
     @projects = Project.all
     @uploader = Project.new.image
     @uploader.success_action_redirect = new_project_url
  end

  def new
     @project = Project.new(key: params[:key])
  end

  def create
    @project = Project.new(params[:project])
    if @project.save
      flash[:notice] = "Project has been created."
      redirect_to @project
    else
      flash[:notice] = "Project could not be saved"
      render action: "new"
    end
  end

  def show
      @project = Project.find(params[:id])
      @commentable = @project
      @comments = @commentable.comments
      @comment = Comment.new
  end

  def edit
    @project = Project.find(params[:id])
  end

  def update
    @project = Project.find(params[:id])

    if @project.update_attributes(params[:project])
      redirect_to @project, notice: 'Project was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @project = Project.find(params[:id])
    @project.destroy

    redirect_to projects_path
  end


private

  def set_project
    @project = Project.find(params[:id])
  end

  def project_params
    params.require(:project).permit(:name, :technologies_used)
  end

end

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.hidden_field :key %>

  <p>File: <%= @project.image_name %></p>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :technologies_used %><br />
    <%= f.text_area :technologies_used %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/_project.html.erb
<div class="project">
  <% if project.image_processed? %>
    <%= link_to image_tag(project.image_url(:thumb)), project if project.image? %>
  <% else %>
    <em>Processing...</em>
  <% end %>
  <div class="name"><%= project.name %></div>
  <div class="actions">
    <%= link_to "edit", edit_project_path(project) %> |
    <%= link_to "remove", project, :confirm => 'Are you sure?', :method => :delete %>
  </div>
</div>

app/views/projects/edit.html.erb
<h1>Edit Project</h1>

<%= render 'form' %>

<%= link_to "Cancel", :back %>

app/views/projects/index.html.erb
<% @projects.each do |project| %>
  <div class="project" id="<%= dom_id(project) %>">
    <h3><%= project.name %></h3>
    <p><%= project.technologies_used %></p>
    <div class="nav">
      <%= link_to 'Show', project %> |
      <%= link_to 'Edit', edit_project_path(project) %> |
      <%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %>
    </div>
  </div>
<% end %>

<%= s3_uploader_form post: projects_url, as: "project[image_url]" do %>
  <%= file_field_tag :file, multiple: true %>
<% end %>

<script id="template-upload" type="text/x-tmpl">
<div class="upload">
  {%=o.name%}
  <div class="progress"><div class="bar" style="width: 0%"></div></div>
</div>
</script>

<%= direct_upload_form_for @uploader do |f| %>
  <p><%= f.file_field :image %></p>
  <p><%= f.submit "Upload Image" %></p>
<% end %>

<br />
<%= link_to 'New project', new_project_path %>

app/views/projects/new.html.erb
<h1>New project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<h2><%= @project.name %></h2>
<p>Technologies used: <%= @project.technologies_used %></p>
<%= image_tag @project.image_url(:thumb).to_s %>

<%= render "comments/form" %>