config/routes.rb
Portfolio::Application.routes.draw do
  scope ":locale" do

    devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks"}

    resources :posts do
      resources :comments
    end

    resources :projects do
      resources :comments
    end

    devise_scope :user do
      get 'sign_out', to: 'devise/sessions#destroy', as: :sign_out
    end

  end
   root :to => 'home#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <title>Phil Worthington</title>

  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

  <!-- Font Awesome -->
  <link href="//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.min.css" rel="stylesheet">

  <link href='http://fonts.googleapis.com/css?family=Source+Sans+Pro:200,400,600,700' rel='stylesheet' type='text/css'>


</head>

<body>

    <% flash.each do |key, value| %>
      <div class="<%= flash_class(key) %>">
        <%= value %>
      </div>
    <% end %>

   <!--  <% if current_user.present? %>
      <%= link_to 'Sign Out', sign_out_path %>
      <% else %>
      <%= link_to 'Sign Up', new_user_registration_path %>
      <%= link_to 'Sign In', new_user_session_path %>
      <%= link_to "Sign in with Twitter", user_omniauth_authorize_path(:twitter) %>
    <% end %> -->

    <%= yield %>


  </body>

</html>